import sys, subprocess, json
p = subprocess.Popen([sys.executable, 'main.py'], stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
p.stdin.write('{\"jsonrpc\": \"2.0\", \"id\": 1, \"method\": \"initialize\", \"params\": {\"protocolVersion\": \"2024-11-05\", \"capabilities\": {}, \"clientInfo\": {\"name\": \"test\", \"version\": \"1.0\"}}}\n')
p.stdin.flush()
print('Init reply:', p.stdout.readline().strip())
p.stdin.write('{\"jsonrpc\": \"2.0\", \"method\": \"notifications/initialized\"}\n')
p.stdin.flush()
p.stdin.write('{\"jsonrpc\": \"2.0\", \"id\": 2, \"method\": \"tools/call\", \"params\": {\"name\": \"execute_python_code\", \"arguments\": {\"code\": \"print(1)\"}}}\n')
p.stdin.flush()
print('Tool reply:', p.stdout.readline().strip())
p.terminate()
